version: '3.9'

services:
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "3001:3001"
    env_file:
      - ./auth-service/.env
    depends_on:
      - database-service
    networks:
      - backend

  database-service:
    build: ./database-service
    container_name: database-service
    ports:
      - "3004:3004"
    env_file:
      - ./database-service/.env
    depends_on:
      - mysql
    networks:
      - backend

  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: escape_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  adminer:
    image: adminer
    container_name: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data: