name: CI/CD Docker Microservices

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      REGISTRY: docker.io
      IMAGE_PREFIX: august3

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push auth-service
        run: |
          docker build -t $REGISTRY/$IMAGE_PREFIX/auth-service ./auth-service
          docker push $REGISTRY/$IMAGE_PREFIX/auth-service

      - name: Build and push booking-service
        run: |
          docker build -t $REGISTRY/$IMAGE_PREFIX/booking-service ./booking-service
          docker push $REGISTRY/$IMAGE_PREFIX/booking-service

      - name: Build and push database-service
        run: |
          docker build -t $REGISTRY/$IMAGE_PREFIX/database-service ./database-service
          docker push $REGISTRY/$IMAGE_PREFIX/database-service

      - name: Build and push notification-service
        run: |
          docker build -t $REGISTRY/$IMAGE_PREFIX/notification-service ./notification-service
          docker push $REGISTRY/$IMAGE_PREFIX/notification-service

